apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: shonfa24i-python-gitops
  description: This is GitOps manifest for shonfa24i-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=shonfa24i-python
    backstage.io/kubernetes-id: shonfa24i-python 
    backstage.io/techdocs-ref: dir:. 
    github.com/project-slug: tnevrlka-rhtap/shonfa24i-python-gitops   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:shonfa24i-python
