apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: shonfa24i-python
  janus-idp.io/tekton: shonfa24i-python
  backstage.io/kubernetes-id: shonfa24i-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: shonfa24i-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
